### ISSUE TITLE
Key derivation not working

### ISSUE THREAD

**Issue by metamarcdw** [metamarcdw/nowallet#1]
Getting an error during key derivation. Occurring on Ubuntu using Python 3.5.2.

```
2017-12-12 20:38:40,276 INFO: Deriving keys...
Traceback (most recent call last):
  File "nowallet.py", line 1065, in <module>
    main()
  File "nowallet.py", line 1029, in main
    wallet = Wallet(email, passphrase, connection, loop, chain)  # type: Wallet
  File "nowallet.py", line 293, in __init__
    create_root_keys(salt, passphrase)
  File "nowallet.py", line 214, in inner
    func(*args, **kwargs)
  File "nowallet.py", line 270, in create_root_keys
    t = derive_key(salt, passphrase)  # type: Tuple[int, bytes]
  File "/home/user/nowallet/nowallet/keys.py", line 38, in derive_key
    digestmodule=hashlib.sha256).read(key_length)  # type: bytes
  File "/home/user/.local/lib/python3.5/site-packages/pbkdf2.py", line 161, in read
    block = self.__f(i)
  File "/home/user/.local/lib/python3.5/site-packages/pbkdf2.py", line 173, in __f
    U = self.__prf(self.__passphrase, self.__salt + pack("!L", i))
  File "/home/user/.local/lib/python3.5/site-packages/pbkdf2.py", line 146, in _pseudorandom
    digestmod=self.__digestmodule).digest()
  File "/usr/lib/python3/dist-packages/Crypto/Hash/HMAC.py", line 211, in new
    return HMAC(key, msg, digestmod)
  File "/usr/lib/python3/dist-packages/Crypto/Hash/HMAC.py", line 105, in __init__
    self.outer = digestmod.new()
AttributeError: 'builtin_function_or_method' object has no attribute 'new'
```

**Comment by metamarcdw** [comment]
*Going to start using tox to test all supported versions of Python*.
Probably going to use pycrypto here instead of hashlib.

**Comment by mmortal03** [comment]
So, I tried it on Ubuntu 17.10, which has Python 3.6.3

First off, separate issue, I noticed that running make init gives me:  RuntimeError: aiohttp requires Python 3.4.2+
even though I have 3.6.3. Is the make init trying to use Python 2.7 pip by accident?
To get around this, I had to install pip3 and then manually ran: pip3 install -r requirements.txt

This completed successfully, but I haven't looked at the make file to see if it still had stuff to do after that

Then I ran the following: 
cd nowallet
python3 nowallet.py

That gets me as far as I got on Mint, without having to comment out ClassVar, but I still get the same digestmod.new() error, even with 3.6.3 on Ubuntu

**Comment by metamarcdw** [comment]
Switched to pycrypto in 6fffd2e04889378c54c294e707b183791509f191 and got rid of ClassVar stuff because it wasn't correct anyway. Go ahead and do a git pull and see if it works for you. Still haven't got tox going yet.

**Comment by mmortal03** [comment]
Ok, everything is working now. On a fresh Linux Mint 18.3 machine, this is what I needed to do to get it working from scratch, while avoiding any confusing error messages for people:

sudo apt install git tor python3-dev python3-pip libssl-dev
git clone https://github.com/metamarcdw/nowallet.git
sudo -H pip3 install --upgrade pip
sudo -H pip3 install setuptools
cd nowallet
sudo -H make init
cd nowallet
python3 nowallet.py

**Comment by metamarcdw** [comment]
README is looking better!
39d1ab4acefa2d2fedad2573a17124d37eccd923
