### ISSUE TITLE
New UI

### ISSUE THREAD

**Issue by theREALaltoid** [metamarcdw/nowallet#11]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
A redone UI. 

**Describe alternatives you've considered**
I've retooled it and added dark mode. 

**Additional context**
Here's the repo with the changed files: https://github.com/theREALaltoid/NWWEB-UI

**Comment by metamarcdw** [comment]
Hello!
It seems like this issue was meant for the website repo.
You can find it located at: https://github.com/metamarcdw/nwweb
Please feel free to make a pull request there. Thanks!
