### ISSUE TITLE
New spends not appearing in history

### ISSUE THREAD

**Issue by metamarcdw** [metamarcdw/nowallet#12]
**Describe the bug**
On spending, new unconfirmed 'Sent' transactions never appear in tx history.

**To Reproduce**
1. Run nowallet using any interface
2. Spend test coins
3. Wait for new tx to appear in history
4. See nothing happen

**Expected behavior**
A new entry should appear in the tx history as a spend.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04 bionic
 - Interface: All
 - Version: current tip of master branch https://github.com/metamarcdw/nowallet/commit/c35f33a32be247c52962afb817dfc03f1be7d2ab

**Additional context**
Python 3.6.5

**Comment by hkrugersa** [comment]
Hi @metamarcdw , 

First time contribution, hopefully first of many :-) I believe that I've found the source of the issue in the `_dispatch_result` method. 

In the method, only the first transaction (i.e. `history[0]`)  received from the `get_history` RPC call is checked. Hence, only the output to the address is processed and not the subsequent transaction where the funds are spent. 

I tested the change on testnet and it seems to be working as can be seen in the screenshot below. You should see that the TxID is included with a height of 0 in the third block of print_loop outputs below it. 

![image](https://user-images.githubusercontent.com/44502799/50928328-10578600-1463-11e9-917a-7d7235a6d84e.png)

I've added the for loop and I'm ready to submit the pull request, but in keeping to the guidelines in CONTRIBUTING.md - I just wanted to get the go ahead first and/or discuss any additional changes or corrections that may be required.

**Comment by hkrugersa** [comment]
Updated code can be viewed at https://github.com/metamarcdw/nowallet/compare/master...hkrugersa:master?diff=unified

**Comment by metamarcdw** [comment]
This looks good. Thanks a ton for contributing!

I am in the midst of preparing for a cross country move and a new job, so please forgive me for any delays. I am going to try to make some time to test this tomorrow afternoon. Please feel free to submit the PR whenever you like.

Thanks again!

**Comment by hkrugersa** [comment]
Thanks @metamarcdw 

I've submitted the pull request, please let me know if you have any further questions. 

Congrats on landing the new job and best of luck with the move!
