### ISSUE TITLE
Lock with PIN UI not working

### ISSUE THREAD

**Issue by xavierfiechter** [metamarcdw/nowallet#15]
See screenshot
![Bildschirmfoto 2019-04-09 um 22 02 38](https://user-images.githubusercontent.com/31884704/55831408-5203d580-5b13-11e9-9d89-571c300cb776.png)

**Comment by metamarcdw** [comment]
Is this on a simulator, or is it running from source?

**Comment by xavierfiechter** [comment]
Running on mac OS.

**Comment by metamarcdw** [comment]
See replies on #16
