### ISSUE TITLE
Base UI broken is simulator.

### ISSUE THREAD

**Issue by xavierfiechter** [metamarcdw/nowallet#16]
It seems that the core is working OK, but the UI has some serious problems.

"login" screen for key derivation 

![Bildschirmfoto 2019-04-09 um 22 07 13](https://user-images.githubusercontent.com/31884704/55831707-0ef63200-5b14-11e9-89d7-755ec1d66f55.png)

main menu when keys OK is missing (buttons), settings menu as well

![Bildschirmfoto 2019-04-09 um 22 09 45](https://user-images.githubusercontent.com/31884704/55831782-3816c280-5b14-11e9-8b67-178fa4916616.png)

**Comment by xavierfiechter** [comment]
See #15 as well

**Comment by metamarcdw** [comment]
This probably has something to do with the fact that KivyMD only supports Linux. Based on your screenshots I suspect you are on a Mac. This is actually stated in the README on their Gitlab repo:
https://gitlab.com/kivymd/KivyMD/blob/master/README.md

**Comment by xavierfiechter** [comment]
OK, but Kivy is platform agnostic, see https://kivy.org/doc/stable/installation/installation-osx.html

**Comment by metamarcdw** [comment]
It definitely is. If you are so inclined, you could probably get KivyMD to install and work correctly on MacOS, but it's probably easier to use Ubuntu, because that's what is tested and supported right now.
