### ISSUE TITLE
New Logo Design For Nowallet

### ISSUE THREAD

**Issue by zularizal** [metamarcdw/nowallet#3]
Hi @metamarcdw ,I am a graphic designer, I want to help others in graphic design.

After I review your project, your app is very good. But I think your icon is irrelevant to your application. Therefore I suggest a new logo and icon for you. If you want it, I will design it for you and it's free.

**Comment by zularizal** [comment]
Hi, I've designed some logos for you, what do you think? which one do you like?

If there is something you want to change please let me know

![logo](https://user-images.githubusercontent.com/38547278/42251222-2dd60d70-7f60-11e8-9b58-f15d462c8d8d.png)

**Comment by metamarcdw** [comment]
The first is definitely my favorite. Thank you very much for contributing!

**Comment by zularizal** [comment]
Hi, I've uploaded the logo to the drive, check this link

https://drive.google.com/open?id=1-VWpr8WIws0kSKYW44922l2Rpd9avlZE

and also I have sent a pull request for you #4

**Comment by metamarcdw** [comment]
Perfect! I love it. Thanks again for your help.

**Comment by metamarcdw** [comment]
I have changed the icon to your new design and re-rendered the screenshots. I also added the logo to the http://nowallet.org website.
